### ISSUE TITLE
sentence-transformers semantic-search

### ISSUE THREAD

**Issue by garbanlp** [Matesanz/oktopus#2]
El usuario va a buscar y en esta primera iteracción se va a hacer un semantic-search normal, es decir, dada una question que nos devuelva un ranking de documentos y su score.

Se van a usar embeddings para hacer dense-retrieval. Por tanto, primero hay que definir el modelo que va generar embeddings ( aka Embedder )

```
text -> vector
```

Por otro lado se van a usar ( en esta primera instancia ) documentos precargados, que tienen que estar vectorizados ( y habrá que probar con distintos chunks del texto ). Eso se cargará en qdrant y finalmente se hará coseno similaridad

Pasos a seguir son:

- [x] Tener un sample de documentos
- [x] instalar sentences-transformers
- [x] instalar qdrant
- [x] elegir tipo de embeder
- [x] elegir tipo de chunks
- [x] guardar los chunks en qdrant
- [x] probar question-answering

**Comment by Matesanz** [comment]
closed in #15
